-- ============================================================================
-- LWCAM Database Schema
-- ============================================================================


-- ============================================================================
-- Shared updated_at trigger function
-- ============================================================================

CREATE OR REPLACE FUNCTION public.lwcam_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := clock_timestamp();
    RETURN NEW;
END;
$$;


-- ============================================================================
-- Role registry
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.roles (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    role_name  VARCHAR(255) NOT NULL UNIQUE
);


-- ============================================================================
-- Users
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id               VARCHAR(255) NOT NULL UNIQUE,

    password              VARCHAR(255) NOT NULL,
                          /* bcrypt hash (the app's existing PasswordHasher).
                             Never MD5 — cryptographically broken for
                             passwords. */

    active                BOOLEAN NOT NULL DEFAULT TRUE,

    must_change_password  BOOLEAN NOT NULL DEFAULT TRUE,

    created_at            TIMESTAMPTZ(3) NOT NULL
                              DEFAULT clock_timestamp(),

    created_by            BIGINT,

    last_login_at         TIMESTAMPTZ(3),

    device_id             VARCHAR(255),
                          /* The capture device (SAX##) assigned to this
                             account — required for capture-role users,
                             NULL otherwise. Owned by LWCam Admin.
                             Uniqueness is enforced by a PARTIAL unique
                             index (see the index section) so a
                             soft-deleted account's device id can be
                             reassigned to a new account. */

    roles                 VARCHAR(255) NOT NULL DEFAULT '',
                          /* Comma-separated global roles, e.g. 'admin',
                             'capture', or 'admin,capture'. This is the
                             account's role independent of any project
                             assignment — user_projects below still records
                             the per-project role grant for downstream
                             tooling, but an account with zero project
                             assignments must still round-trip with its
                             role intact, which user_projects alone cannot
                             guarantee. */

    updated_at            TIMESTAMPTZ(3) NOT NULL
                              DEFAULT clock_timestamp(),

    updated_by            BIGINT,

    is_deleted            BOOLEAN NOT NULL DEFAULT FALSE,

    deleted_at            TIMESTAMPTZ(3),

    CONSTRAINT fk_users_created_by
        FOREIGN KEY (created_by)
        REFERENCES public.users(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_users_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES public.users(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


-- ============================================================================
-- Projects
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.projects (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    project_id             VARCHAR(255) NOT NULL,
                           /* Unique among LIVE projects only (partial
                              index below) — a soft-deleted project's id
                              may be reused by a new project. */

    project_key            VARCHAR(64) NOT NULL UNIQUE,
                           /* Client-generated, write-once identity
                              ('p' + base36 timestamp+random — see
                              LWCAM/LWCam Admin's Project.key). This is the
                              stable identity boxes/folders/images
                              reference; project_id above is a
                              human-editable label and may be renamed
                              without breaking those references. */

    project_name           VARCHAR(255) NOT NULL,
                           /* Unique among LIVE projects only (partial
                              index below). */

    country_location_code  VARCHAR(32) NOT NULL UNIQUE,
                           /* Mix of country code and location in UI.
                              Stays a FULL unique constraint (unlike
                              project_id/project_name) because
                              fk_devices_country_location references it —
                              an FK target cannot be a partial index.
                              LWCam Admin's soft delete therefore rewrites
                              it to '~deleted~<id>' to free the code for
                              reuse; the devices FK cascades the rewrite,
                              which deliberately leaves any still-bound
                              device blocked until an admin reassigns it. */

    start_date             TIMESTAMPTZ(3),

    has_data               BOOLEAN NOT NULL DEFAULT FALSE,
                           /* Used to record existing projects and indicate
                              their current status. */

    template               JSONB,

    created_at             TIMESTAMPTZ(3) NOT NULL
                               DEFAULT clock_timestamp(),

    created_by             BIGINT,

    updated_at             TIMESTAMPTZ(3) NOT NULL
                               DEFAULT clock_timestamp(),

    updated_by             BIGINT,

    is_deleted             BOOLEAN NOT NULL DEFAULT FALSE,

    deleted_at             TIMESTAMPTZ(3),

    CONSTRAINT fk_projects_created_by
        FOREIGN KEY (created_by)
        REFERENCES public.users(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_projects_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES public.users(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


-- ============================================================================
-- Devices
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.devices (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    device_id              VARCHAR(255) NOT NULL UNIQUE,

    country_location_code  VARCHAR(32) NOT NULL,
                           /* Mix of country code and location in UI */

    user_id                BIGINT,
                           /* Used to record the user who last used
                              the device. */

    login_at               TIMESTAMPTZ(3) NOT NULL
                               DEFAULT clock_timestamp(),

    CONSTRAINT fk_devices_country_location
        FOREIGN KEY (country_location_code)
        REFERENCES public.projects(country_location_code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_devices_user
        FOREIGN KEY (user_id)
        REFERENCES public.users(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


-- ============================================================================
-- User-project-role assignments
-- ============================================================================

/*
Used to record the many-to-many relationship between users and projects.

A user can work on multiple projects, and a project can also be assigned
to multiple users.

A user may hold multiple roles within the same project.

SuperAdmin users do not need to have their project relationships recorded
in this table.
*/

CREATE TABLE IF NOT EXISTS public.user_projects (
    user_id     BIGINT NOT NULL,

    project_id  BIGINT NOT NULL,

    role_id     INT NOT NULL,

    CONSTRAINT pk_user_projects
        PRIMARY KEY (user_id, project_id, role_id),

    CONSTRAINT fk_user_projects_user
        FOREIGN KEY (user_id)
        REFERENCES public.users(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_user_projects_project
        FOREIGN KEY (project_id)
        REFERENCES public.projects(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_user_projects_role
        FOREIGN KEY (role_id)
        REFERENCES public.roles(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


-- ============================================================================
-- Capture boxes
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.capture_boxes (
    box_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    box_name           VARCHAR(255) NOT NULL,
                       /* Duplication check and reminder during operator
                          box details input. */

    device_id          BIGINT NOT NULL,

    status             VARCHAR(255) NOT NULL DEFAULT 'OPEN',
                       /* Used to store information for each capture box
                          and record its current transfer status.
                          Full-caps values: OPEN, TRANSFERRED, REWORK. */

    user_id            BIGINT NOT NULL,

    project_id         BIGINT NOT NULL,

    created_at         TIMESTAMPTZ(3) NOT NULL
                           DEFAULT clock_timestamp(),

    updated_at         TIMESTAMPTZ(3) NOT NULL
                           DEFAULT clock_timestamp(),

    transfer_start_at  TIMESTAMPTZ(3),
                       /* The time the image transfer starts. */

    transfer_end_at    TIMESTAMPTZ(3),
                       /* The time the image transfer ends. */

    transferred_to     VARCHAR(255),
                       /* NAS path */

    is_deleted         BOOLEAN NOT NULL DEFAULT FALSE,

    deleted_at         TIMESTAMPTZ(3),

    CONSTRAINT uq_capture_boxes_project_name
        UNIQUE (project_id, box_name),

    CONSTRAINT fk_capture_boxes_device
        FOREIGN KEY (device_id)
        REFERENCES public.devices(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_capture_boxes_user
        FOREIGN KEY (user_id)
        REFERENCES public.users(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_capture_boxes_project
        FOREIGN KEY (project_id)
        REFERENCES public.projects(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


-- ============================================================================
-- Capture folders
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.capture_folders (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    group_id              VARCHAR(255) UNIQUE,
                          /* Minted at the QC stage from the PG-backed
                             sequence — NULL until QC processes the folder
                             (rows arrive from capture/transfer without it).
                             UNIQUE still forbids duplicate GroupIDs;
                             "WHERE group_id IS NULL" = QC's work queue. */

    folder_name           VARCHAR(255) NOT NULL,

    box_id                BIGINT NOT NULL,

    device_id             BIGINT NOT NULL,

    folder_seq            INTEGER NOT NULL,

    cover_tag             VARCHAR(255),
                          /* All metadata */

    image_tags            VARCHAR(255),

    title                 VARCHAR(255),

    volume                VARCHAR(255),

    start_date            TIMESTAMPTZ(3),

    end_date              TIMESTAMPTZ(3),

    archival_ref_no       VARCHAR(255),

    record_type           VARCHAR(255),

    place                 VARCHAR(255),

    language              VARCHAR(255),

    record_custodian      VARCHAR(255),

    capture_operator_id   VARCHAR(255),

    capture_operator_name VARCHAR(255),

    digitizing_entity     VARCHAR(255),
                          /* All metadata */

    source_created_at     TIMESTAMPTZ(3),

    source_updated_at     TIMESTAMPTZ(3),

    updated_at            TIMESTAMPTZ(3) NOT NULL
                              DEFAULT clock_timestamp(),

    is_deleted            BOOLEAN NOT NULL DEFAULT FALSE,

    deleted_at            TIMESTAMPTZ(3),

    client_qc_status      VARCHAR(20),
                          /* NULL, UNDER REVIEW, APPROVED or REJECTED */

    client_rework         BOOLEAN NOT NULL DEFAULT FALSE,
                          /* Change to TRUE if rejected by the client
                             QC site CSV. */

    is_deskewed           BOOLEAN NOT NULL DEFAULT FALSE,
                          /* Add completion time in log files. */

    is_cropped            BOOLEAN NOT NULL DEFAULT FALSE,
                          /* Add completion time in log files. */

    is_created_thumbnail  BOOLEAN NOT NULL DEFAULT FALSE,
                          /* Add completion time in log files. */

    folder_path           VARCHAR(10800),

    thumbnail_path        VARCHAR(10800),

    qc_status             VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                          /* PASS, REWORK or PENDING */

    is_tif_converted      BOOLEAN NOT NULL DEFAULT FALSE,

    is_exported           BOOLEAN NOT NULL DEFAULT FALSE,

    exported_time         TIMESTAMPTZ(3),

    is_ingested           BOOLEAN NOT NULL DEFAULT FALSE,

    ingested_time         TIMESTAMPTZ(3),

    CONSTRAINT uq_capture_folders_box_sequence
        UNIQUE (box_id, folder_seq),

    CONSTRAINT chk_capture_folders_client_qc_status
        CHECK (
            client_qc_status IS NULL
            OR client_qc_status IN (
                'UNDER REVIEW',
                'APPROVED',
                'REJECTED'
            )
        ),

    CONSTRAINT chk_capture_folders_qc_status
        CHECK (
            qc_status IN (
                'PASS',
                'REWORK',
                'PENDING'
            )
        ),

    CONSTRAINT fk_capture_folders_box
        FOREIGN KEY (box_id)
        REFERENCES public.capture_boxes(box_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_capture_folders_device
        FOREIGN KEY (device_id)
        REFERENCES public.devices(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


-- ============================================================================
-- Capture images
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.capture_images (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    image_name        VARCHAR(255) NOT NULL,
                      /* Use image_name to indicate image files. */

    device_id         BIGINT NOT NULL,

    folder_id         BIGINT NOT NULL,

    file_format       VARCHAR(10) NOT NULL,

    image_created_at  TIMESTAMPTZ(3) NOT NULL
                          DEFAULT clock_timestamp(),

    image_updated_at  TIMESTAMPTZ(3),

    CONSTRAINT uq_capture_images_folder_image
        UNIQUE (folder_id, image_name),

    CONSTRAINT chk_capture_images_file_format
        CHECK (
            LOWER(file_format) IN (
                'jpg',
                'jpeg',
                'tif',
                'tiff',
                'png'
            )
        ),

    CONSTRAINT fk_capture_images_device
        FOREIGN KEY (device_id)
        REFERENCES public.devices(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_capture_images_folder
        FOREIGN KEY (folder_id)
        REFERENCES public.capture_folders(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


-- ============================================================================
-- Rework records
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.rework_logs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     /* Logan will work on this. */

    image_id         BIGINT,
                     /* NULL means the rework applies to the folder generally.
                        A value means the rework applies to a specific image. */

    assigned_uid     BIGINT NOT NULL,
                     /* Can be assigned back to the original operator
                        or assigned to another operator. */

    folder_id        BIGINT NOT NULL,
                     /* Every rework record must belong to one folder. */

    created_at       TIMESTAMPTZ(3) NOT NULL
                         DEFAULT clock_timestamp(),

    rework_comments  VARCHAR(10800) NOT NULL,

    rework_status    VARCHAR(20) NOT NULL DEFAULT 'OPEN',
                     /* e.g. OPEN, CLOSED, etc. */

    rework_type      VARCHAR(255) NOT NULL,
                     /* May use different types of rework, e.g.
                        ReCapture Rework, Image Rework,
                        Separation Rework or Metadata Rework. */

    CONSTRAINT fk_rework_logs_image
        FOREIGN KEY (image_id)
        REFERENCES public.capture_images(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_rework_logs_assigned_user
        FOREIGN KEY (assigned_uid)
        REFERENCES public.users(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_rework_logs_folder
        FOREIGN KEY (folder_id)
        REFERENCES public.capture_folders(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


-- ============================================================================
-- App settings (LWCam Admin-managed key/value store)
-- ============================================================================

/*
Shared configuration that used to live only in the NAS users-store JSON:
metadata keying on/off, remote-shutter config, the store-wide default temp
password, and the SuperAdmin password override. LWCam Admin is the only
writer; LWCAM pulls this table read-only alongside users/projects.

Keys in use: metadata_keying_enabled ('true'/'false'), shutter_keybind,
shutter_method, shutter_tap_x_percent, shutter_tap_y_percent,
default_temp_password_hash (bcrypt), superadmin_password_hash (bcrypt
override — an absent row means "use the factory hash").
*/

CREATE TABLE IF NOT EXISTS public.app_settings (
    key         VARCHAR(255) PRIMARY KEY,

    value       VARCHAR(10800),

    updated_at  TIMESTAMPTZ(3) NOT NULL
                    DEFAULT clock_timestamp()
);


-- ============================================================================
-- Indexes
-- ============================================================================


-- Users

CREATE INDEX IF NOT EXISTS idx_users_created_by
    ON public.users(created_by);

CREATE INDEX IF NOT EXISTS idx_users_updated_by
    ON public.users(updated_by);

/* Unique among LIVE accounts only: a soft-deleted account keeps its
   device_id for audit, but the id must be reassignable to a new account —
   a full UNIQUE would make delete-then-reassign fail forever. */
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_device_id_live
    ON public.users(device_id)
    WHERE is_deleted = FALSE AND device_id IS NOT NULL;


-- Projects

CREATE INDEX IF NOT EXISTS idx_projects_created_by
    ON public.projects(created_by);

CREATE INDEX IF NOT EXISTS idx_projects_updated_by
    ON public.projects(updated_by);

/* Unique among LIVE projects only, same rationale as
   uq_users_device_id_live: a deleted project's human-editable label/name
   must be reusable by a new project (which gets a fresh project_key).
   project_key itself stays a full UNIQUE column constraint — it is the
   upsert conflict target and is never reused. country_location_code also
   stays a full UNIQUE column constraint (it is an FK target — see the
   column comment for how soft delete frees it instead). */
CREATE UNIQUE INDEX IF NOT EXISTS uq_projects_project_id_live
    ON public.projects(project_id)
    WHERE is_deleted = FALSE;

CREATE UNIQUE INDEX IF NOT EXISTS uq_projects_project_name_live
    ON public.projects(project_name)
    WHERE is_deleted = FALSE;


-- Devices

CREATE INDEX IF NOT EXISTS idx_devices_country_location_code
    ON public.devices(country_location_code);

CREATE INDEX IF NOT EXISTS idx_devices_user_id
    ON public.devices(user_id);


-- User-project-role assignments

CREATE INDEX IF NOT EXISTS idx_user_projects_project_id
    ON public.user_projects(project_id);

CREATE INDEX IF NOT EXISTS idx_user_projects_role_id
    ON public.user_projects(role_id);


-- Capture boxes

CREATE INDEX IF NOT EXISTS idx_capture_boxes_device_id
    ON public.capture_boxes(device_id);

CREATE INDEX IF NOT EXISTS idx_capture_boxes_user_id
    ON public.capture_boxes(user_id);


/*
A separate project_id index is unnecessary because the following
unique constraint already creates an index beginning with project_id:

UNIQUE (project_id, box_name)
*/


-- Capture folders

CREATE INDEX IF NOT EXISTS idx_capture_folders_device_id
    ON public.capture_folders(device_id);


/*
A separate box_id index is unnecessary because the following
unique constraint already creates an index beginning with box_id:

UNIQUE (box_id, folder_seq)
*/


-- Capture images

CREATE INDEX IF NOT EXISTS idx_capture_images_image_name
    ON public.capture_images(image_name);

CREATE INDEX IF NOT EXISTS idx_capture_images_device_id
    ON public.capture_images(device_id);


/*
A separate folder_id index is unnecessary because the following
unique constraint already creates an index beginning with folder_id:

UNIQUE (folder_id, image_name)
*/


-- Rework records

CREATE INDEX IF NOT EXISTS idx_rework_logs_image_id
    ON public.rework_logs(image_id);

CREATE INDEX IF NOT EXISTS idx_rework_logs_folder_id
    ON public.rework_logs(folder_id);

CREATE INDEX IF NOT EXISTS idx_rework_logs_assigned_uid
    ON public.rework_logs(assigned_uid);


/*
App settings needs no secondary index — it is looked up and iterated
entirely by its own primary key (key).
*/


-- ============================================================================
-- updated_at triggers
-- ============================================================================


-- Users

DROP TRIGGER IF EXISTS trg_users_updated_at
ON public.users;

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON public.users
FOR EACH ROW
EXECUTE FUNCTION public.lwcam_set_updated_at();


-- Projects

DROP TRIGGER IF EXISTS trg_projects_updated_at
ON public.projects;

CREATE TRIGGER trg_projects_updated_at
BEFORE UPDATE ON public.projects
FOR EACH ROW
EXECUTE FUNCTION public.lwcam_set_updated_at();


-- Capture boxes

DROP TRIGGER IF EXISTS trg_capture_boxes_updated_at
ON public.capture_boxes;

CREATE TRIGGER trg_capture_boxes_updated_at
BEFORE UPDATE ON public.capture_boxes
FOR EACH ROW
EXECUTE FUNCTION public.lwcam_set_updated_at();


-- Capture folders

DROP TRIGGER IF EXISTS trg_capture_folders_updated_at
ON public.capture_folders;

CREATE TRIGGER trg_capture_folders_updated_at
BEFORE UPDATE ON public.capture_folders
FOR EACH ROW
EXECUTE FUNCTION public.lwcam_set_updated_at();


-- App settings

DROP TRIGGER IF EXISTS trg_app_settings_updated_at
ON public.app_settings;

CREATE TRIGGER trg_app_settings_updated_at
BEFORE UPDATE ON public.app_settings
FOR EACH ROW
EXECUTE FUNCTION public.lwcam_set_updated_at();


-- ============================================================================
-- Upgrade note (2026-07-21 schema v2)
-- ============================================================================

/*
This file uses CREATE TABLE IF NOT EXISTS throughout, so re-running it
against an existing database only adds app_settings and does nothing else.
Per the project's fresh-v1 convention (R&D, no shipped installs), the
expected upgrade path for the v2 changes below is DROP AND RECREATE the
database from this file:

  - users.device_id / users.roles (new nullable/defaulted columns — safe to
    add either way, but a fresh DB is simplest).
  - projects.project_key (NOT NULL UNIQUE — cannot be added to a table with
    existing rows without a backfill). If live project data must survive a
    schema bump instead of a fresh recreate, backfill every existing row's
    project_key from that project's LWCAM/LWCam Admin JSON store record
    BEFORE the first push after the upgrade, or the push will attempt to
    insert duplicates that fail the project_id UNIQUE constraint.
  - 2026-07-21 (later, same day): users.device_id, projects.project_id and
    projects.project_name switched from full UNIQUE constraints to PARTIAL
    unique indexes (WHERE is_deleted = FALSE) so a soft-deleted row's
    values can be reused by a new account/project — a full UNIQUE made
    delete-then-recreate wedge LWCam Admin's push permanently.
    country_location_code stays full UNIQUE (FK target from devices);
    LWCam Admin's projectSoftDeleteSql frees it by rewriting it to
    '~deleted~<id>' instead. Same drop-and-recreate upgrade path.
*/