BEGIN;

CREATE TABLE IF NOT EXISTS public.qc_status (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id    BIGINT NOT NULL REFERENCES public.capture_folders(id)
                 ON DELETE RESTRICT ON UPDATE CASCADE,
    user_id      VARCHAR(255) NOT NULL REFERENCES public.users(user_id)
                 ON DELETE RESTRICT ON UPDATE CASCADE,
    status       VARCHAR(20) NOT NULL,
    details      JSONB NOT NULL DEFAULT '{}'::jsonb,
    started_at   TIMESTAMPTZ(3) NOT NULL DEFAULT clock_timestamp(),
    completed_at TIMESTAMPTZ(3),
    updated_at   TIMESTAMPTZ(3) NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT chk_qc_status_status
        CHECK (status IN ('REVIEWING', 'COMPLETED', 'RELEASED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_qc_status_active_folder
    ON public.qc_status(folder_id)
    WHERE status = 'REVIEWING';

CREATE UNIQUE INDEX IF NOT EXISTS uq_qc_status_active_user
    ON public.qc_status(user_id)
    WHERE status = 'REVIEWING';

CREATE INDEX IF NOT EXISTS idx_qc_status_folder_history
    ON public.qc_status(folder_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_qc_status_user_history
    ON public.qc_status(user_id, completed_at DESC);

DROP TRIGGER IF EXISTS trg_qc_status_updated_at ON public.qc_status;
CREATE TRIGGER trg_qc_status_updated_at
BEFORE UPDATE ON public.qc_status
FOR EACH ROW EXECUTE PROCEDURE public.lwcam_set_updated_at();

COMMIT;
